## multirotor_utils.gd
## Stateless math helpers for the multirotor (drone) flight model.
##
## These mirror the building blocks used by real multirotor flight controllers
## (PID stabilisation, motor mixing and force/torque resolution) but are kept
## *pure* – no node state, no globals – so the flight dynamics in
## `FDMInterface._step_multirotor` stay deterministic and every formula can be
## exercised directly by the unit tests in `tests/test_multirotor_utils.gd`.
##
## Motor index convention (quad in the "X" layout), viewed from above with the
## nose pointing +pitch:
##   0 = front-right (CCW)   1 = front-left  (CW)
##   2 = rear-right  (CW)    3 = rear-left   (CCW)
## Command sign convention used by [method mix_quad_x]:
##   roll  > 0  -> roll right (left motors speed up)
##   pitch > 0  -> pitch nose up (rear motors speed up)
##   yaw   > 0  -> yaw right (CW-spinning motors speed up)
class_name MultirotorUtils
extends RefCounted

## Quad "X" motor indices (see class docs for the layout diagram).
const MOTOR_FRONT_RIGHT := 0
const MOTOR_FRONT_LEFT  := 1
const MOTOR_REAR_RIGHT  := 2
const MOTOR_REAR_LEFT   := 3

## Advance a single-axis PID controller by one step.
## Returns a Dictionary with the new "output" plus the updated "integral" and
## "prev_error" so the caller can persist controller state between frames.
## [param i_limit] clamps the integral term to prevent wind-up.
static func pid_step(error: float, prev_error: float, integral: float,
		kp: float, ki: float, kd: float, delta: float,
		i_limit: float = 1.0) -> Dictionary:
	var dt := maxf(delta, 0.0)
	var new_integral := integral
	var derivative := 0.0
	if dt > 0.0:
		new_integral = clampf(integral + error * dt, -i_limit, i_limit)
		derivative = (error - prev_error) / dt
	var output := kp * error + ki * new_integral + kd * derivative
	return {
		"output": output,
		"integral": new_integral,
		"prev_error": error,
	}

## Mix collective throttle and roll/pitch/yaw commands into four motor outputs
## for a quad in the "X" layout. Each command is expected in roughly [-1, 1]
## (throttle in [0, 1]); outputs are clamped to [0, 1]. See the class docs for
## the index and sign conventions.
static func mix_quad_x(throttle: float, roll: float, pitch: float, yaw: float) -> PackedFloat32Array:
	var motors := PackedFloat32Array([0.0, 0.0, 0.0, 0.0])
	# front-right (CCW): roll right -> slower, nose up -> slower, yaw right -> slower
	motors[MOTOR_FRONT_RIGHT] = throttle - roll - pitch - yaw
	# front-left (CW):  roll right -> faster, nose up -> slower, yaw right -> faster
	motors[MOTOR_FRONT_LEFT]  = throttle + roll - pitch + yaw
	# rear-right (CW):  roll right -> slower, nose up -> faster, yaw right -> faster
	motors[MOTOR_REAR_RIGHT]  = throttle - roll + pitch + yaw
	# rear-left (CCW):  roll right -> faster, nose up -> faster, yaw right -> slower
	motors[MOTOR_REAR_LEFT]   = throttle + roll + pitch - yaw
	for i in motors.size():
		motors[i] = clampf(motors[i], 0.0, 1.0)
	return motors

## Total upward thrust (N, along the body up axis) produced by the motors.
static func total_thrust(motors: PackedFloat32Array, thrust_per_motor_n: float) -> float:
	var sum := 0.0
	for m in motors:
		sum += m
	return sum * thrust_per_motor_n

## Resolve the body-frame torque vector (N·m) generated by motor thrust
## differentials, returned as Vector3(roll, pitch, yaw).
## [param arm_m] is the horizontal distance from the centre to each motor.
## [param yaw_torque_coef] scales motor thrust into reaction (drag) torque about
## the yaw axis. Signs follow the conventions documented for [method mix_quad_x].
static func motors_to_body_torque(motors: PackedFloat32Array, arm_m: float,
		thrust_per_motor_n: float, yaw_torque_coef: float) -> Vector3:
	if motors.size() < 4:
		return Vector3.ZERO
	var fr := motors[MOTOR_FRONT_RIGHT] * thrust_per_motor_n
	var fl := motors[MOTOR_FRONT_LEFT]  * thrust_per_motor_n
	var rr := motors[MOTOR_REAR_RIGHT]  * thrust_per_motor_n
	var rl := motors[MOTOR_REAR_LEFT]   * thrust_per_motor_n
	# Roll: left motors vs right motors. Pitch: rear motors vs front motors.
	var roll_torque := arm_m * ((fl + rl) - (fr + rr))
	var pitch_torque := arm_m * ((rr + rl) - (fr + fl))
	# Yaw: reaction torque from CW vs CCW motors (FL & RR spin CW).
	var yaw_torque := yaw_torque_coef * ((fl + rr) - (fr + rl))
	return Vector3(roll_torque, pitch_torque, yaw_torque)

## Hover throttle fraction that exactly cancels gravity, given the per-motor
## thrust and number of motors. Returns a value in [0, 1] (1.0 if the craft is
## under-powered and cannot hover). Useful for throttle expo / altitude assist.
static func hover_throttle(mass_kg: float, thrust_per_motor_n: float,
		motor_count: int, gravity: float = 9.81) -> float:
	var max_thrust := thrust_per_motor_n * maxf(float(motor_count), 1.0)
	if max_thrust <= 0.0:
		return 1.0
	return clampf((mass_kg * gravity) / max_thrust, 0.0, 1.0)
